# tmux setup playbook
#
#   ansible-tmux.yml
---
- name: emacs setup
  hosts: all
  tasks:
    - name: check mandatory variables are defined
      assert:
        that:
          - user is defined
    - name: install ansible
      command: pip3 install ansible
    - name: install pgcli
      command: pip3 install pgcli
    - name: install icdiff
      command: pip3 install icdiff